version: '3.8'

services:
   # Main app. Builds from Dockerfile
    app:
        build:
            context: .
        depends_on:
            - db
        ports:
            - "8000:8000"

    # Postgres database. Contains the database for the app.
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: seqwrc
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgresql/data