version: '3.8'

services:
    app:
        build:
            context: .
        depends_on:
            - db

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: seqwrc
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgresql/data

volumes:
    pgdata: